### ISSUE TITLE
个人语料训练不是以关键字为主的，感觉逻辑有点问题

### ISSUE THREAD

**Issue by richor1042** [learnmedicalcantsavecn/chatbot#1]
比如我的语料：Q:你几岁  A：我三岁
机器人会训练完，跑出来的是不含“你几岁”这三个字的问题的回复

**Comment by ximinng** [comment]
“你几岁”这个Question会被jieba分词，之后feed进模型，也就是说feed的是词向量，逻辑没有问题，我想知道您训练了多少epoch？train or train_ant？以及模型具体参数是什么？你的个人语料是以什么形式添加的？这些问题可能帮助解决您的问题！
